version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/ruby:2.5.1-stretch-node-browsers
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    parallelism: 4
    steps:
      - checkout
      - run: bundle check || bundle install
      - run:
          command: |
            TESTFILES=$(circleci tests glob "test/tests/*.rb" | circleci tests split --split-by=filesize)
            bundle exec ruby -e 'ARGV.each {|f| require File.join(".", f) }' -- $TESTFILES
